config/routes.rb
BraintreeRailsExample::Application.routes.draw do
  resources :users do
    resource :customer do
      resources :credit_cards do
        resources :transactions, except: [:edit, :destroy]
        resources :subscriptions
      end
      resources :addresses
      resources :transactions, except: [:edit, :destroy]
    end
  end
  resources :transactions, except: [:edit, :destroy]
  resources :plans, only: [:index, :show] do
    resources :subscriptions
  end
  resources :add_ons, only: [:index, :show]
  resources :discounts, only: [:index, :show]
  resources :subscriptions, except: [:new, :create]
  resources :history_events, only: :index
  root to: 'users#index'
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_filter :find_user, :find_customer
  before_filter :find_credit_card, except: [:new, :create]

  def index
    @credit_cards = @customer.credit_cards
  end

  def new
    billing_address = @customer.addresses.first || {}
    @credit_card = @customer.credit_cards.build({cardholder_name: @customer.full_name, billing_address: billing_address})
  end

  def edit; end

  def show; end

  def create
    @credit_card = @customer.credit_cards.build(params[:credit_card].merge(params.slice(:device_data)))
    if @credit_card.save
      flash[:notice] = "Credit card has been successfully updated."
      redirect_to user_customer_credit_card_path(@user, @credit_card)
    else
      flash[:alert] = @credit_card.errors.full_messages.join(".\n")
      render :new
    end
  end

  def update
    if @credit_card.update_attributes(params[:credit_card].merge(params.slice(:device_data)))
      flash[:notice] = "Credit card has been successfully updated."
      redirect_to user_customer_credit_card_path(@user, @credit_card) and return
    else
      flash[:alert] = @credit_card.errors.full_messages.join(".\n")
      render :edit
    end
  end

  def destroy
    @credit_card.destroy
    flash[:notice] = "Credit card has been successfully deleted."
    redirect_to user_customer_credit_cards_path(@user)
  end

  protected
  def find_user
    @user = User.find(params[:user_id])
  end

  def find_customer
    @customer = @user.customer
    redirect_to user_path(@user) and return if @customer.nil?
  end

  def find_credit_card
    @credit_card = @customer.credit_cards.find(params[:id])
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
  def options_for_month_select
    {
      collection: Date::MONTHNAMES.each_with_index.to_a[1..-1].map { |month, index| [month, index.to_s.rjust(2, '0')]},
      include_blank: false,
    }
  end

  def options_for_year_select
    {
       collection: 1976..2200,
       include_blank: false,
    }
  end
end

app/views/credit_cards/_form.html.haml
= simple_form_for @credit_card, url: url, html: { class: 'form-horizontal', id: 'braintree-credit-card-form' } do |f|
  = f.input(:number, input_html: { 'data-encrypted-name' => true }) if @credit_card.new_record?
  = f.input :cardholder_name
  = f.input(:cvv, maxlength: 4, input_html: {'data-encrypted-name' => true }) if @credit_card.new_record?
  = f.input :expiration_month, options_for_month_select
  = f.input :expiration_year, options_for_year_select
  = f.simple_fields_for :billing_address, @credit_card.billing_address do |ba|
    = ba.input :first_name
    = ba.input :last_name
    = ba.input :company
    = ba.input :street_address
    = ba.input :extended_address
    = ba.input :locality
    = ba.input :country_code_alpha2, options_for_country_select
    = ba.input :region, options_for_region_select
    = ba.input :postal_code
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', user_customer_credit_cards_path(@user), class: 'btn'

- content_for :javascript do
  :javascript
    var braintree = Braintree.create("#{BraintreeRails::Configuration.client_side_encryption_key}")
    braintree.onSubmitEncryptForm('braintree-credit-card-form');
    BraintreeData.setup("#{BraintreeRails::Configuration.merchant_id}", "braintree-credit-card-form", BraintreeData.environments.sandbox)
    BraintreeData.setup("#{BraintreeRails::Configuration.merchant_id}", "braintree-transaction-form", BraintreeData.environments.sandbox)

app/views/credit_cards/edit.html.haml
- model_class = BraintreeRails::CreditCard
.page-header
  %h1="Edit #{model_class.model_name.human}"
= render partial: "form", locals: {url: user_customer_credit_card_path(@user, @credit_card)}

app/views/credit_cards/index.html.haml
- model_class = BraintreeRails::CreditCard
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:card_type)
      %th= model_class.human_attribute_name(:masked_number)
      %th= model_class.human_attribute_name(:cardholder_name)
      %th= model_class.human_attribute_name(:expiration_date)
      %th= 'Actions'
  %tbody
    - @credit_cards.each do |credit_card|
      %tr
        %td= credit_card.card_type
        %td= link_to credit_card.masked_number, user_customer_credit_card_path(@user, credit_card)
        %td= credit_card.cardholder_name
        %td= credit_card.expiration_date
        %td
          = link_to 'Edit', edit_user_customer_credit_card_path(@user, credit_card), class: 'btn btn-mini'
          = link_to 'Destroy', user_customer_credit_card_path(@user, credit_card), method: :delete, data: {confirm:'Are you sure?'}, class: 'btn btn-mini btn-danger'

= link_to 'Back', user_customer_path(@user), class: 'btn'
= link_to 'New', new_user_customer_credit_card_path(@user), class: 'btn btn-primary'

app/views/credit_cards/new.html.haml
- model_class = BraintreeRails::CreditCard
.page-header
  %h1="New #{model_class.model_name.human}"
= render partial: "form", locals: {url: user_customer_credit_cards_path(@user)}

app/views/credit_cards/show.html.haml
- model_class = BraintreeRails::CreditCard
.page-header
  %h1=t '.title', default: model_class.model_name.human
- [:card_type, :masked_number, :cardholder_name, :expiration_date].each do |attribute|
  %p
    %strong= model_class.human_attribute_name(attribute) + ':'
    %br
    = @credit_card.send(attribute)
- [:first_name, :last_name, :company, :street_address, :extended_address, :locality, :region, :postal_code, :country_name].each do |billing_address_attribute|
  %p
    %strong= BraintreeRails::Address.human_attribute_name(billing_address_attribute) + ':'
    %br
    = @credit_card.billing_address.send(billing_address_attribute) if @credit_card.billing_address

.form-actions
  = link_to 'Back', user_customer_credit_cards_path(@user), class: 'btn'
  = link_to 'Edit', edit_user_customer_credit_card_path(@user, @credit_card), class: 'btn'
  = link_to 'Transactions', user_customer_credit_card_transactions_path(@user, @credit_card), class: 'btn'
  = link_to 'Subscriptions', user_customer_credit_card_subscriptions_path(@user, @credit_card), class: 'btn'
  = link_to 'Destroy', user_customer_credit_card_path(@user, @credit_card), method: "delete", data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'