config/routes.rb
BraintreeRailsExample::Application.routes.draw do
  resources :users do
    resource :customer do
      resources :credit_cards do
        resources :transactions, except: [:edit, :destroy]
        resources :subscriptions
      end
      resources :addresses
      resources :transactions, except: [:edit, :destroy]
    end
  end
  resources :transactions, except: [:edit, :destroy]
  resources :plans, only: [:index, :show] do
    resources :subscriptions
  end
  resources :add_ons, only: [:index, :show]
  resources :discounts, only: [:index, :show]
  resources :subscriptions, except: [:new, :create]
  resources :history_events, only: :index
  root to: 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, uniqueness: true, presence: true
  after_destroy :destroy_customer

  def customer
    customer_id && BraintreeRails::Customer.new(customer_id)
  end

  private
  def destroy_customer
    BraintreeRails::Customer.delete(customer_id) if customer_id.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit; end

  def show; end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash.now[:alert] = @user.errors.full_messages.join(".\n")
      render action: "new"
    end
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      flash.now[:alert] = @user.errors.full_messages.join(".\n")
      render action: "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, html: { class: 'form-horizontal' } do |f|
  = f.input :email
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', users_path, class: 'btn'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1="Edit #{model_class.model_name.human}"
= render partial: "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', default: model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:email)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', default: t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.id, user_path(user)
        %td= link_to user.email, user_path(user)
        %td= user.created_at
        %td
          = link_to 'Edit', edit_user_path(user), class: 'btn btn-mini'
          = link_to 'Destroy', user_path(user), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-mini btn-danger'

= link_to 'New', new_user_path, class: 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1="New #{model_class.model_name.human}"
= render partial: "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', default: model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:email) + ':'
  %br
  = @user.email

.form-actions
  = link_to 'Back', users_path, class: 'btn'
  = link_to 'Edit', edit_user_path(@user), class: 'btn'
  = link_to 'Customer info', user_customer_path(@user), class: 'btn'
  = link_to 'Destroy', user_path(@user), method: 'delete', data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'