config/routes.rb
BraintreeRailsExample::Application.routes.draw do
  resources :users do
    resource :customer do
      resources :credit_cards do
        resources :transactions, except: [:edit, :destroy]
        resources :subscriptions
      end
      resources :addresses
      resources :transactions, except: [:edit, :destroy]
    end
  end
  resources :transactions, except: [:edit, :destroy]
  resources :plans, only: [:index, :show] do
    resources :subscriptions
  end
  resources :add_ons, only: [:index, :show]
  resources :discounts, only: [:index, :show]
  resources :subscriptions, except: [:new, :create]
  resources :history_events, only: :index
  root to: 'users#index'
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_filter :find_user
  before_filter :find_customer, except: [:new, :create]

  def new
    @customer = BraintreeRails::Customer.new(email: @user.email)
  end

  def create
    @customer = BraintreeRails::Customer.new(params[:customer].merge(params.slice(:device_data)))
    if @customer.save
      @user.update_attribute(:customer_id, @customer.id)
      flash[:notice] = "Customer has been successfully created."
      redirect_to user_customer_path(@user) and return
    else
      flash[:alert] = @customer.errors.full_messages.join(".\n")
      render :new
    end
  end

  def show
    if @customer.nil?
      redirect_to new_user_customer_path(@user) and return
    end
  end

  def edit; end

  def update
    if @customer.update_attributes(params[:customer].merge(params.slice(:device_data)))
      flash[:notice] = "Customer has been successfully updated."
      redirect_to user_customer_path(@user) and return
    else
      flash[:alert] = @customer.errors.full_messages.join(".\n")
      render :edit
    end
  end

  def destroy
    @customer.destroy
    @user.update_attribute(:customer_id, nil)
    flash[:notice] = "Customer has been successfully deleted."
    redirect_to user_path(@user)
  end

  protected
  def find_user
    @user = User.find(params[:user_id])
  end

  def find_customer
    @customer = @user.customer
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.haml
= simple_form_for @customer, url: user_customer_path(@user), html: { class: 'form-horizontal' } do |f|
  - [:first_name, :last_name, :email, :company, :website, :phone, :fax].each do |attribute|
    = f.input attribute
  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', user_path(@user), class: 'btn'

- content_for :javascript do
  :javascript
    BraintreeData.setup("#{BraintreeRails::Configuration.merchant_id}", "braintree-transaction-form", BraintreeData.environments.sandbox)

app/views/customers/edit.html.haml
- model_class = BraintreeRails::Customer
.page-header
  %h1="Edit #{model_class.model_name.human}"
= render partial: "form"

app/views/customers/new.html.haml
- model_class = BraintreeRails::Customer
.page-header
  %h1="New #{model_class.model_name.human}"
= render partial: "form"

app/views/customers/show.html.haml
- model_class = BraintreeRails::Customer
.page-header
  %h1=t '.title', default: model_class.model_name.human
- [:first_name, :last_name, :email, :company, :website, :phone, :fax].each do |attribute|
  %p
    %strong= model_class.human_attribute_name(attribute) + ':'
    %br
    = @customer.send(attribute)

.form-actions
  = link_to 'Back', users_path, class: 'btn'
  = link_to 'Edit', edit_user_customer_path(@user), class: 'btn'
  = link_to 'Transactions', user_customer_transactions_path(@user), class: 'btn'
  = link_to 'Credit cards', user_customer_credit_cards_path(@user), class: 'btn'
  = link_to 'Addresses', user_customer_addresses_path(@user), class: 'btn'
  = link_to 'Destroy', user_customer_path(@user), method: "delete", data: {confirm: 'Are you sure?'}, class: 'btn btn-danger'