config/routes.rb
BraintreeRailsExample::Application.routes.draw do
  resources :users do
    resource :customer do
      resources :credit_cards do
        resources :transactions, except: [:edit, :destroy]
        resources :subscriptions
      end
      resources :addresses
      resources :transactions, except: [:edit, :destroy]
    end
  end
  resources :transactions, except: [:edit, :destroy]
  resources :plans, only: [:index, :show] do
    resources :subscriptions
  end
  resources :add_ons, only: [:index, :show]
  resources :discounts, only: [:index, :show]
  resources :subscriptions, except: [:new, :create]
  resources :history_events, only: :index
  root to: 'users#index'
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "BraintreeRailsExample"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Braintree Rails Example
          .container.nav-collapse
            %ul.nav
              %li= link_to("Users", users_path)
              %li= link_to("Transactions", transactions_path)
              %li= link_to("Plans", plans_path)
              %li= link_to("AddOns", add_ons_path)
              %li= link_to("Discounts", discounts_path)
              %li= link_to("Subscriptions", subscriptions_path)
              %li= link_to("History Events", history_events_path)
              %li= link_to("Source Code", "https://github.com/lyang/braintree-rails-example")

    .container
      = bootstrap_flash
      .content
        .row
          .span9
            = yield
          .span3
            .well.sidebar-nav
              %a.github{href: "https://github.com/lyang/braintree-rails"}
                %img{alt: "Fork me on GitHub", src: "https://s3.amazonaws.com/github/ribbons/forkme_right_orange_ff7600.png"}
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to("Users", users_path)
                %li= link_to("Transactions", transactions_path)
                %li= link_to("Plans", plans_path)
                %li= link_to("AddOns", add_ons_path)
                %li= link_to("Discounts", discounts_path)
                %li= link_to("Subscriptions", subscriptions_path)
                %li= link_to("History Events", history_events_path)
                %li= link_to("Source Code", "https://github.com/lyang/braintree-rails-example")

      %footer
        %p &copy; Company 2014
    = yield :javascript